name: Generate and Commit Files

on:
  workflow_dispatch:

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Make scripts executable
        run: |
          find . -name "*.sh" -type f -exec chmod +x {} \;
          find . -name "*.py" -type f -exec chmod +x {} \;

      - name: Run all generate scripts
        run: |
          # Find and run all Python files that start with "generate"
          for file in generate*.py; do
            if [ -f "$file" ]; then
              echo "Running $file..."
              python "$file"
            fi
          done

          # Find and run all shell scripts that start with "generate"
          for file in generate*.sh; do
            if [ -f "$file" ]; then
              echo "Running $file..."
              ./"$file"
            fi
          done

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          # Get current date and time
          DATETIME=$(date '+%Y-%m-%d %H:%M:%S')

          # Add all JSON and log files
          git add *.json *.log

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            # Commit with action name and timestamp
            git commit -m "Generate and Commit Files - $DATETIME"
            git push
          fi
