name: Update Timetable Data

on:
  schedule:
    # Run every 4 hours during school days (Monday-Friday, 6 AM to 6 PM AEST)
    - cron: '0 20,0,4,8 * * 1-5'  # 6 AM, 10 AM, 2 PM, 6 PM AEST (UTC+10)
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-timetable:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Run timetable update script
        run: python update_timetable.py
